export const ROUTES: string[] = [

  '/',
  '/contacts',
  '/about',
  '/favorites',
  '/privacy-policy',
  '/sitemap',
  '/owners',
  '/services/tbs',

  '/gorod',
  '/gorod/zhilye-kompleksy',
  '/gorod/zhilye-kompleksy/:id',
  '/gorod/kvartira',
  '/gorod/kvartira/:id',
  '/gorod/dom',
  '/gorod/dom/:id',
  '/gorod/taunhaus',
  '/gorod/taunhaus/:id',
  '/gorod/penthaus',
  '/gorod/penthaus/:id',
  '/gorod/novostroyki',
  '/gorod/novostroyki/:id',
  '/gorod/arenda',
  '/gorod/kvartira/metro',
  '/gorod/discount',
  '/gorod/apartments',
  '/gorod/apartments/:id',

  '/gorod/:category1',
  '/gorod/:category1/:category2',
  '/gorod/:category1/:category2/:category3',
  '/gorod/:category1/:category2/:category3/:category4',

  '/zagorod',
  '/zagorod/dom',
  '/zagorod/dom/:id',
  '/zagorod/kvartira',
  '/zagorod/kvartira/:id',
  '/zagorod/taunhaus',
  '/zagorod/taunhaus/:id',
  '/zagorod/uchastok',
  '/zagorod/uchastok/:id',
  '/zagorod/poselki',
  '/zagorod/poselki/:id',
  '/zagorod/arenda',
  '/zagorod/discount',

  '/zagorod/:category1',
  '/zagorod/:category1/:category2',
  '/zagorod/:category1/:category2/:category3',
  '/zagorod/:category1/:category2/:category3/:category4',

  '/office',
  '/office/business-center',
  '/office/business-center/:id',
  '/office/osobnyak',
  '/office/osobnyak/:id',
  '/office/mnogofunkcionalnyy-kompleks',
  '/office/mnogofunkcionalnyy-kompleks/:id',
  '/office/business-park',
  '/office/business-park/:id',
  '/office/arenda',

  '/office/:category1/',
  '/office/:category1/:category2',
  '/office/:category1/:category2/:category3',
  '/office/:category1/:category2/:category3/:category4',

  '/retail',
  '/retail/street_retail/:id',
  '/retail/:category1',

  '/retail/rental-business',
  '/retail/arenda',
  '/retail/prodazha',

  '/skladi',
  '/skladi/:category1',
  '/skladi/:category1/:category2',
  '/skladi/:category1/:category2/:category3',
  '/skladi/:category1/:category2/:category3/:category4',

  '/skladi/prodazha',
  '/skladi/arenda',
  '/skladi/arenda',

  '/zarubezhnaya',
  '/zarubezhnaya/:category1',
  '/zarubezhnaya/:category1/:category2',

  '/zarubezhnaya/dom',
  '/zarubezhnaya/villa',
  '/zarubezhnaya/apartments',
  '/zarubezhnaya/shale',
  '/zarubezhnaya/commercial',
  '/zarubezhnaya/penthaus',
  '/zarubezhnaya/taunhaus',
  '/zarubezhnaya/citizenship',

  '/map/:category1',
  '/map/:category1/:category2',
  '/map/:category1/:category2/:category3',
  '/map/:category1/:category2/:category3/:category4',

];
